### ISSUE TITLE
Please report any issues here

### ISSUE THREAD

**Issue by dportik** [dportik/SuperCRUNCH#1]
Please report any bugs, problems, or issues you may have found while using SuperCRUNCH. I am trying to actively maintain this project and will do my best to address them in a timely manner. Thanks for using SuperCRUNCH!

**Comment by cromanpa94** [comment]
Dear developer,

I had the following when running the `Cluster_Blast_Extract.py` script in MacOs (El Capitan & Mojave). Cd-hit was originally installed using homebrew (`brew install cd-hit`).

```
Here's the problem in case you're curious:
dyld: Symbol not found: __ZdlPvm
  Referenced from: /usr/local/bin/cd-hit-est
  Expected in: /usr/lib/libstdc++.6.dylib
 in /usr/local/bin/cd-hit-est
```

The issue got solved by simply installing cd-hit through conda:

`conda install -c bioconda cd-hit`

Thanks!
