### ISSUE TITLE
Reference_Blast_Extract.py using prebuilt blastdb or blast result

### ISSUE THREAD

**Issue by Ufungi** [dportik/SuperCRUNCH#12]
Dear dportik

My reference fasta file is too large (GenBank nt database), so I wonder if there is a way to run Reference_Blast_Extract.py using prebuilt blastdb, or just trimming query sequences using blast result file without running blast from the start.

Thank you.

Best regards, Shinnam Yoo

**Comment by dportik** [comment]
Hello @Ufungi ,
The `Reference_Blast_Extract.py` module is intended to be run with a small number of reference sequences. The use-case is to identify particular loci. 

I am not sure what the use-case would be that would involved using the entire GenBank database as the reference file. Could you describe this better? I might be able to point you to a tool that will accomplish what you are looking for instead.
