### ISSUE TITLE
Unexpected error in Taxa_Assessment.py

### ISSUE THREAD

**Issue by ericgoolsby** [dportik/SuperCRUNCH#6]
Hi Dan,

I'm not familiar with writing sqlite3 queries, but on line 241 of Taxa_Assessment.py (the elif statement dealing with subspecies), the apostrophe after ({0}) seems to be throwing an error.:

`cur.execute("SELECT * FROM records WHERE sspname IN ({0})'".format(qseq))
`

I tried removing the apostrophe, i.e.:

`cur.execute("SELECT * FROM records WHERE sspname IN ({0})".format(qseq))
`

However, then the error is replaced by

`sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.`

I've worked around it simply by avoiding subspecies. I'm unsure if it's a problem limited to some pathology in my sequence names or if it's a general issue. In case of the latter I wanted to raise it here.

Thanks!

Best,
Eric

**Comment by dportik** [comment]
Hi Eric,
Thanks for your message. There was a copy/paste error in this section of the code that was causing the sqlite3 error, it had nothing to do with your dataset. I just updated the code and tested it - it should be working properly now. If you have any other questions or encounter further errors, please let me know and I'll help as best I can!
