### ISSUE TITLE
Basic usage

### ISSUE THREAD

**Issue by cromanpa94** [dportik/SuperCRUNCH#7]
Hey Dan!

You may wanna check the basic usage for several scripts (in the Wiki). For instance, the current basic usage for Adjust_Direction.py is: 

"python -i <input directory> -o <output directory>"

I found the same issue for a handful of scrips in pages 7 (Multiple Sequence Alignment) and 8 (Post Alignment Tasks). Everything else looks great! 😄

**Comment by dportik** [comment]
Hi Cristian!
Thanks for bringing this to my attention - there were indeed some missing components there! I went ahead and fixed the ones I found... please let me know if there are any more. I'll close this issue for now.
