### ISSUE TITLE
Trim_Alignments_Custom.py - ImportError: Bio.Alphabet has been removed from Biopython

### ISSUE THREAD

**Issue by sarah-ravioli** [dportik/SuperCRUNCH#9]
Hi Dan,

I've been trying to trim the edges of sequences post-alignment using Trim_Alignments_Custom.py:

> python Trim_Alignments_Custom.py
> -i ~/Desktop/pheromone\ diversity/data/Lepidoptera/Geometridae\ supercrunch/attempt\ 2/step_7_output/2021.03.26/step_7a_output/MAFFT/Relabeled-by-species/Relabeled-fasta-files
> -o ~/Desktop/pheromone\ diversity/data/Lepidoptera/Geometridae\ supercrunch/attempt\ 2/step_7_output/2021.03.26/step_7b_output/MAFFT_edgesonly
> -a edges 
> -f fasta

However, I get the following error message: 

> Traceback (most recent call last):
>   File "Trim_Alignments_Custom.py", line 58, in <module>
>     from Bio.Alphabet import IUPAC, Gapped
>   File "/Users/sarahravoth/miniconda3/envs/supercrunch/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
>     "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
> ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

I've already run the same fasta files through Trim_Alignments_Trimal.py with no issues. I'm working in Python 3.9 on MacOS 10.15.7, using the supercrunch conda environment you provided. I've attached one of the fasta files I'm working with below. I was wondering whether you have a suggestion on how to solve or work around this problem? Thanks for your help!

[cMDH_extracted_oneseq_Adjusted_Passed_MAFFT_Aligned_relabeled.fasta.zip](https://github.com/dportik/SuperCRUNCH/files/6216501/cMDH_extracted_oneseq_Adjusted_Passed_MAFFT_Aligned_relabeled.fasta.zip)

**Comment by dportik** [comment]
Hello @sarah-ravioli,
Thanks for reporting this issue. It seems that the newest version of BioPython (1.78) eliminated one of the biopython modules required for the `Trim_Alignments_Custom.py` routine, and this is the source of the problem.

I have updated the conda env file to require BioPython version 1.77, rather than look for the most recent version (1.78+). BioPython 1.77 was the version used to develop and test SuperCRUNCH. 

If you delete your current supercrunch conda environment, then re-install the environment using the updated file, this should hopefully solve the issue. Please let me know if this works, or if you continue to have issues. Thanks!

**Comment by sarah-ravioli** [comment]
Thanks for your response! I recreated the supercrunch environment using the update, and it seems to have cleared up the previous issue. However, I'm getting a different error now, using the same command and files as above:

> NameError: name 'xrange' is not defined

**Comment by dportik** [comment]
Hi @sarah-ravioli,
Thanks for also reporting this error. There was a compatibility issue with python2 to python3 in the `Trim_Alignments_Custom.py` module, and I just added a fix for this. I tested it with your data and it ran successfully. Please download the newest version of `Trim_Alignments_Custom.py`, and let me know if have any other issues.

**Comment by sarah-ravioli** [comment]
Everything's running smoothly. Thanks for your help!
